apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: peder-edc2019
spec:
  environments:
    - name: development
      build:
        from: master
    - name: qa
      build:
        from: master
    - name: prod
  components:
    - name: www
      src: ./www
      publicPort: http
      ports:
       - name: http
         port: 3000
      environmentConfig:
        - environment: development
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 1
        - environment: qa
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 1
        - environment: prod
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 2
    - name: echo
      src: ./echo
      ports:
       - name: http
         port: 3001
      environmentConfig:
        - environment: development
          monitoring: true
          variables:
            PORT: 3001
            NODE_ENV: production
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "54Mi"
              cpu: "200m"
          replicas: 2
        - environment: qa
          monitoring: true
          variables:
            PORT: 3001
            NODE_ENV: production
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "54Mi"
              cpu: "200m"
          replicas: 2
        - environment: prod
          monitoring: true
          variables:
            PORT: 3001
            NODE_ENV: production
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "54Mi"
              cpu: "200m"
          replicas: 5
  dnsAppAlias:
    environment: development
    component: www
